repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
    -   id: flake8
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: name-tests-test
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v1.3.4
    hooks:
    -   id: reorder-python-imports
